//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Thu Oct  8 20:22:34 2020 by ROOT version 6.20/02)
//      from the StreamerInfo in file /home/stephen/hex/berk/edep/new/edep-sim/output/output1001.root
//////////////////////////////////////////////////////////


#ifndef __pair_base_string_vector_TG4HitSegment____h
#define __pair_base_string_vector_TG4HitSegment____h
#include <vector>
namespace std {} using namespace std;
class TG4HitSegment;
template <typename T0, typename T1> class __pair_base;
template <> class __pair_base<string,vector<TG4HitSegment> >;

namespace std {} using namespace std;
#include "TG4HitSegment.h"

#ifndef template___pair_base_h
#define template___pair_base_h
template <typename T0, typename T1> class __pair_base {

public:
// Nested classes declaration.

public:
// Data Members.

   __pair_base() {
   }
   __pair_base(__pair_base && ) = default;
   __pair_base(const __pair_base & rhs )
{
   // This is NOT a copy constructor. This is actually a move constructor (for stl container's sake).
   // Use at your own risk!
   (void)rhs; // avoid warning about unused parameter
   }
   virtual ~__pair_base() {
   }

};
#endif // generic template declaration
#endif
