//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Thu Oct  8 20:22:34 2020 by ROOT version 6.20/02)
//      from the StreamerInfo in file /home/stephen/hex/berk/edep/new/edep-sim/output/output1001.root
//////////////////////////////////////////////////////////


#ifndef TG4PrimaryParticle_h
#define TG4PrimaryParticle_h
class TG4PrimaryParticle;

#include "Rtypes.h"
#include "TObject.h"
#include "Riostream.h"
#include <string>
#include "TLorentzVector.h"

class TG4PrimaryParticle : public TObject {

public:
// Nested classes declaration.

public:
// Data Members.
   int         TrackId;     //
   string      Name;        //
   int         PDGCode;     //
   TLorentzVector Momentum;    //

   TG4PrimaryParticle();
   TG4PrimaryParticle(TG4PrimaryParticle && ) = default;
   TG4PrimaryParticle(const TG4PrimaryParticle & );
   virtual ~TG4PrimaryParticle();

   ClassDef(TG4PrimaryParticle,2); // Generated by MakeProject.
};
#endif
