//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Thu Oct  8 20:22:34 2020 by ROOT version 6.20/02)
//      from the StreamerInfo in file /home/stephen/hex/berk/edep/new/edep-sim/output/output1001.root
//////////////////////////////////////////////////////////


#ifndef TG4PrimaryVertex_h
#define TG4PrimaryVertex_h
class TG4PrimaryVertex;

#include "Rtypes.h"
#include "TObject.h"
#include "Riostream.h"
#include <vector>
#include "TG4PrimaryParticle.h"
#include "TG4PrimaryVertex.h"
#include "TLorentzVector.h"
#include <string>

class TG4PrimaryVertex : public TObject {

public:
// Nested classes declaration.

public:
// Data Members.
   vector<TG4PrimaryParticle> Particles;    //
   vector<TG4PrimaryVertex>   Informational;    //
   TLorentzVector             Position;         //
   string                     GeneratorName;    //
   string                     Reaction;         //
   string                     Filename;         //
   int                        InteractionNumber;    //
   float                      CrossSection;         //
   float                      DiffCrossSection;     //
   float                      Weight;               //
   float                      Probability;          //

   TG4PrimaryVertex();
   TG4PrimaryVertex(TG4PrimaryVertex && ) = default;
   TG4PrimaryVertex(const TG4PrimaryVertex & );
   virtual ~TG4PrimaryVertex();

   ClassDef(TG4PrimaryVertex,3); // Generated by MakeProject.
};
#endif
