//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Thu Oct  8 20:22:34 2020 by ROOT version 6.20/02)
//      from the StreamerInfo in file /home/stephen/hex/berk/edep/new/edep-sim/output/output1001.root
//////////////////////////////////////////////////////////


#ifndef TG4Trajectory_h
#define TG4Trajectory_h
class TG4Trajectory;

#include "Rtypes.h"
#include "TObject.h"
#include "Riostream.h"
#include <vector>
#include "TG4TrajectoryPoint.h"
#include <string>
#include "TLorentzVector.h"

class TG4Trajectory : public TObject {

public:
// Nested classes declaration.

public:
// Data Members.
   vector<TG4TrajectoryPoint> Points;      //
   int                        TrackId;     //
   int                        ParentId;    //
   string                     Name;        //
   int                        PDGCode;     //
   TLorentzVector             InitialMomentum;    //

   TG4Trajectory();
   TG4Trajectory(TG4Trajectory && ) = default;
   TG4Trajectory(const TG4Trajectory & );
   virtual ~TG4Trajectory();

   ClassDef(TG4Trajectory,2); // Generated by MakeProject.
};
#endif
