//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Thu Oct  8 20:22:34 2020 by ROOT version 6.20/02)
//      from the StreamerInfo in file /home/stephen/hex/berk/edep/new/edep-sim/output/output1001.root
//////////////////////////////////////////////////////////


#ifndef TG4TrajectoryPoint_h
#define TG4TrajectoryPoint_h
class TG4TrajectoryPoint;

#include "Rtypes.h"
#include "TObject.h"
#include "TLorentzVector.h"
#include "TVector3.h"

class TG4TrajectoryPoint : public TObject {

public:
// Nested classes declaration.

public:
// Data Members.
   TLorentzVector Position;    //
   TVector3       Momentum;    //
   int            Process;     //
   int            Subprocess;    //

   TG4TrajectoryPoint();
   TG4TrajectoryPoint(TG4TrajectoryPoint && ) = default;
   TG4TrajectoryPoint(const TG4TrajectoryPoint & );
   virtual ~TG4TrajectoryPoint();

   ClassDef(TG4TrajectoryPoint,2); // Generated by MakeProject.
};
#endif
